# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: active_aws 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "active_aws"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alistair A. Israel"]
  s.date = "2015-06-07"
  s.description = "Provides utility classes, helpers and decorators to the AWS Ruby SDK v2"
  s.email = "aisrael@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "READMEmd"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "READMEmd",
    "Rakefile",
    "VERSION",
    "features/cloud_formation/cloud_formation.feature",
    "features/cloud_formation/dsl/parameterized_initializer.feature",
    "features/cloud_formation/dsl/properties.feature",
    "features/cloud_formation/dsl/resource_definition.feature",
    "features/cloud_formation/templates/ec2_instances.feature",
    "features/ec2/client/ec2_client.feature",
    "features/step_definitions/common_steps.rb",
    "features/step_definitions/ec2_client_steps.rb",
    "features/support/env.rb",
    "features/support/vcr.rb",
    "fixtures/vcr_cassettes/ActiveAws_EC2_client_feature/It_has_instances_.yml",
    "fixtures/vcr_cassettes/ActiveAws_EC2_client_feature/It_has_regions_.yml",
    "lib/active_aws.rb",
    "lib/active_aws/cloud_formation.rb",
    "lib/active_aws/cloud_formation/template.rb",
    "lib/active_aws/cloud_formation/template/dsl_block.rb",
    "lib/active_aws/cloud_formation/template/mappings.rb",
    "lib/active_aws/cloud_formation/template/parameter.rb",
    "lib/active_aws/cloud_formation/template/properties.rb",
    "lib/active_aws/cloud_formation/template/resource.rb",
    "lib/active_aws/cloud_formation/template/resource/auto_scaling_group.rb",
    "lib/active_aws/cloud_formation/template/resource/ec2_instance.rb",
    "lib/active_aws/cloud_formation/template/resource/launch_config.rb",
    "lib/active_aws/cloud_formation/template/resource/load_balancer.rb",
    "lib/active_aws/cloud_formation/template/resource/metadata.rb",
    "lib/active_aws/ec2.rb",
    "lib/active_aws/parameterized_initializer.rb"
  ]
  s.homepage = "http://github.com/aisrael/active_aws"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Provides utility classes, helpers and decorators to the AWS Ruby SDK v2"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["= 4.2.1"])
      s.add_runtime_dependency(%q<aws-sdk>, ["~> 2.0"])
      s.add_runtime_dependency(%q<dotenv>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<rspec>, ["~> 3.2"])
      s.add_development_dependency(%q<cucumber>, ["~> 2.0"])
      s.add_development_dependency(%q<aruba>, ["= 0.6.2"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
      s.add_development_dependency(%q<vcr>, ["= 2.9.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rubocop>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.2.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.8.7"])
      s.add_development_dependency(%q<redcarpet>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, ["= 4.2.1"])
      s.add_dependency(%q<aws-sdk>, ["~> 2.0"])
      s.add_dependency(%q<dotenv>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<rspec>, ["~> 3.2"])
      s.add_dependency(%q<cucumber>, ["~> 2.0"])
      s.add_dependency(%q<aruba>, ["= 0.6.2"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<vcr>, ["= 2.9.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rubocop>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 4.2.0"])
      s.add_dependency(%q<yard>, ["~> 0.8.7"])
      s.add_dependency(%q<redcarpet>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["= 4.2.1"])
    s.add_dependency(%q<aws-sdk>, ["~> 2.0"])
    s.add_dependency(%q<dotenv>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<rspec>, ["~> 3.2"])
    s.add_dependency(%q<cucumber>, ["~> 2.0"])
    s.add_dependency(%q<aruba>, ["= 0.6.2"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<vcr>, ["= 2.9.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rubocop>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 4.2.0"])
    s.add_dependency(%q<yard>, ["~> 0.8.7"])
    s.add_dependency(%q<redcarpet>, [">= 0"])
  end
end

